spring:
  application:
    name: ms-document
  datasource:
    url: jdbc:postgresql://localhost:5432/db_document
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083
  servlet:
    context-path: /api/documents

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/