spring:
  application:
    name: ms-notification
  datasource:
    url: jdbc:mysql://localhost:3306/db_notification
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8086
  servlet:
    context-path: /api/notifications

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/