spring:
  application:
    name: ms-workflow
  datasource:
    url: jdbc:mysql://localhost:3306/db_workflow
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084
  servlet:
    context-path: /api/workflows

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/